### ISSUE TITLE
[React-18] Warning: findDOMNode is deprecated in StrictMode.

### ISSUE THREAD

**Issue by shehi** [OlegWock/react-local-toast#8]
Another bug that pops up in React-18 (a NextJs app):

![image](https://user-images.githubusercontent.com/653569/199225224-2286ca00-aa97-4142-95cd-4e57b7b1d844.png)

**Comment by OlegWock** [comment]
Yeah, that's because I used quite outdated library for animation in this project (https://reactcommunity.org/react-transition-group/). If someone has energy to rewrite it to any modern alternative, that would be great.

This is only a warning, so it shouldn't break anything in your project

**Comment by shehi** [comment]
Why not use famous [Animate.Css](https://animate.style/)?

**Comment by OlegWock** [comment]
Because they achieve two different goals. Animate.css is just a preset of ready-made CSS animations while react-transition-group exposes 'state' of component (just mounted, going to be unmounted, etc) which in turn enables us to use CSS animation

**Comment by shehi** [comment]
Well, as they day, we have "a good effort, bad result" at hand. This
eventually will render your package low value if not useless. Just an
observation, no pun intended.

**Comment by OlegWock** [comment]
Fixed in v2 (also compatible with React 19 now)
