### ISSUE TITLE
[Deps] Outdated @radix-ui/react-slot and @radix-ui/react-compose-refs versions not compatible with React-18

### ISSUE THREAD

**Issue by shehi** [OlegWock/react-local-toast#9]
Hi,

Is it possible to upgrade `@radix-ui/react-slot` and `@radix-ui/react-compose-refs` to their v1.0.x which are React-18 compatible? Thanks.

**Comment by OlegWock** [comment]
Are there any problems with current deps and react 18?

**Comment by shehi** [comment]
Yea, as I mentioned above: not R18 compatible. You can check their
package.json file there.

**Comment by OlegWock** [comment]
Migrated to alternative package in v2
